apiVersion: 1

datasources:
  # Jaeger data source for traces (running in docker-compose)
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: true
    editable: true

  # Prometheus data source for metrics (running in docker-compose)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
