version: "3.8"

services:
  wiremock:
    image: "wiremock/wiremock:3.13.1"
    container_name: orlando-wiremock
    ports:
      - "9091:8080"
    volumes:
      - ./wiremock-mappings.json:/home/wiremock/mappings/mappings.json:ro
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
      ]
